-- Seed intentionally left empty.
--
-- This repository no longer ships demo/mock business data.
-- Persisted records must come from the real ingestion flow and PostgreSQL
-- remains the source of truth.
